databases:
  - name: tasty-bites
    databaseName: tasty_bites
    user: tasty_bites_user

services:
  - type: web
    name: tasty-bites
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tasty_bites
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false